services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: systech_aidd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

