services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: systech_aidd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5

  bot:
    image: ghcr.io/eugene-d-evelop/systech-aidd-bot:latest
    command: [ "uv", "run", "python", "-m", "src.main" ]
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/systech_aidd
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  api:
    image: ghcr.io/eugene-d-evelop/systech-aidd-api:latest
    command: [ "uv", "run", "python", "-m", "src.api_main" ]
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/systech_aidd
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: ghcr.io/eugene-d-evelop/systech-aidd-frontend:latest
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      # Для server-side запросов используем внутреннее имя сервиса
      API_URL: http://api:8000
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:


